name: Food Karma
favicon: null
layout_spectrum: 0.7912382676731795
typography_spectrum: 1
title: Share with the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7119120047427714
  lightness: 0.5670259690377861
  saturation: 0.29284684360027313
  rhythmicContrast: 0.34548147954046726
purpose: []
